version: '3'

services:
  workspace:
    image: eg_dock
    build: ./
    volumes:
      - ./src:/var/www/html
    ports:
      - "5000:80"
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci && cp /usr/my.cnf /etc/my.cnf
    ports:
      - "4000:4000"
    environment:
      - DB_PORT=4000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/mysql_data:/var/lib/mysql
