version: '3'

services:
  workspace:
    image: eg_dock
    build: ./
    volumes:
      - ./src:/var/www/html
    ports:
      - "${WORKSPACE_PORT}:80"
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "${DB_PORT}:3306"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./db/mysql_data:/var/lib/mysql
